trigger:
  branches:
    include:
     - master
  paths:
    include:
     - AdvancedDisplayFilter/*
 
pool: Studio-OX
 
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution : '**/Sdl.Community.AdvancedDisplayFilter.sln'
  pluginName: 'AdvancedDisplayFilter'
  
steps:
  - template: include-buid-steps.yml
 
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: $(pluginName).sdlplugin'
    inputs:
     ArtifactName: '$(pluginName).sdlplugin'
     publishLocation: FilePath
     TargetPath: '$(Agent.BuildDirectory)'