# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
     - master
  paths:
   include:
     - Sdl-Community/ApplyStudioProjectTemplate/*

pool: Studio-OX

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution : '**/Sdl.Community.ApplyStudioProjectTemplate.sln'
  
steps:
  - template: include-buid-steps.yml
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ApplyStudioProjectTemplate.SdlPlugin.zip'
    inputs:
     ArtifactName: 'ApplyStudioProjectTemplate.SdlPlugin'
     publishLocation: FilePath
     TargetPath: '$(Agent.BuildDirectory)'

  






