# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core




pool: mypool

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution : 'AHK plugin/Sdl.Community.AhkPlugin/Sdl.Community.AhkPlugin.sln'
steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.5.3'
  inputs:
    versionSpec: 4.5.3


- task: VSBuild@1
  displayName: 'Build solution '
  inputs:
    solution: '$(solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    maximumCpuCount: true

  






